apiVersion: v1
kind: Service
metadata:
  name: management-service
spec:
  type: LoadBalancer
  ports:
  - port: 6002
    targetPort: 6002
    name: coord-query
  # - port: 5002
  #   targetPort: 5002
  #   name: func-call
  # - port: 7800
  #   targetPort: 7800
  #   name: bucket-op
  # - port: 7900
  #   targetPort: 7900
  #   name: trigger-op
  selector:
    role: management
